; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
boards_dir = boards

[env:esp32-s3-eth-8di-8ro-c]
platform = espressif32
;board = freenove_esp32_s3_wroom
board = waveshare_esp32s3_eth
framework = arduino
monitor_speed = 115200
;monitor_port = /dev/tty.usbmodem3101
;upload_port = /dev/tty.usbmodem3101
;build_flags = -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
  hideakitai/ArduinoOSC
  bblanchon/ArduinoJson
